# Generated by Django 4.1.6 on 2023-05-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budjet_amount', models.CharField(max_length=255, null=True, verbose_name='PERCENT')),
                ('percent', models.CharField(max_length=255, null=True, verbose_name='PERCENT')),
                ('bonus', models.CharField(max_length=255, null=True, verbose_name='BONUS')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='FIRST NAME')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='NAME')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SECOND NAME')),
                ('selery', models.CharField(max_length=255, null=True, verbose_name='SELERY')),
                ('adress', models.CharField(max_length=255, null=True, verbose_name='ADDRESSS')),
                ('phone_number', models.CharField(max_length=255, null=True, verbose_name='PHONE NUMBER')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employeers',
            },
        ),
        migrations.CreateModel(
            name='Error_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(blank=True, max_length=255, null=True, verbose_name='Error')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Products_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='NAME')),
                ('amount', models.CharField(max_length=255, null=True, verbose_name='AMOUNT')),
                ('sum', models.CharField(max_length=255, null=True, verbose_name='SUM')),
            ],
            options={
                'verbose_name': 'Finished product',
                'verbose_name_plural': 'Finished products',
            },
        ),
        migrations.CreateModel(
            name='Job_Title_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True, verbose_name='JOB TITLE')),
            ],
            options={
                'verbose_name': 'Job title',
                'verbose_name_plural': 'Job titles',
            },
        ),
        migrations.CreateModel(
            name='Unit_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='UNIT')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Sale_Of_Products_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, null=True, verbose_name='AMOUNT')),
                ('sum', models.CharField(max_length=255, null=True, verbose_name='SUM')),
                ('date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_sp', to='onoxo.employee_model', verbose_name='EMPLOYEE')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onoxo.finished_products_model', verbose_name='PRODUCT')),
            ],
            options={
                'verbose_name': 'Sale of product',
                'verbose_name_plural': 'Sale of products',
            },
        ),
        migrations.CreateModel(
            name='Salary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year and Month')),
                ('numberOfParticip_Purchase', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Of Participations in Purchase')),
                ('numberOfParticip_Production', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Of Participations in Production')),
                ('numberOfParticip_Sale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Of Participations in Sale')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Num Of All Participations ')),
                ('bonus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бонус')),
                ('oklad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оклад')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salary')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_sp1', to='onoxo.employee_model', verbose_name='EMPLOYEE')),
            ],
            options={
                'verbose_name': 'Salary for employee',
                'verbose_name_plural': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Raw_Material_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='NAME')),
                ('amount', models.CharField(max_length=255, null=True, verbose_name='AMOUNT')),
                ('sum', models.CharField(max_length=255, null=True, verbose_name='SUM')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_mat', to='onoxo.unit_model', verbose_name='UNIT')),
            ],
            options={
                'verbose_name': 'Raw material',
                'verbose_name_plural': 'Raw materials',
            },
        ),
        migrations.CreateModel(
            name='Purchase_Raw_Material_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, null=True, verbose_name='AMOUNT')),
                ('sum', models.CharField(max_length=255, null=True, verbose_name='SUM')),
                ('date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_pr', to='onoxo.employee_model', verbose_name='EMPLOYEE')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onoxo.raw_material_model', verbose_name='RAW MATERIAL')),
            ],
            options={
                'verbose_name': 'Purchase Raw Material',
                'verbose_name_plural': 'Purchase Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='Production_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, null=True, verbose_name='AMOUNT')),
                ('date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_p', to='onoxo.employee_model', verbose_name='EMPLOYEE')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onoxo.finished_products_model', verbose_name='PRODUCT')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
            },
        ),
        migrations.CreateModel(
            name='Inqredients_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, null=True, verbose_name='AMOUNT')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onoxo.finished_products_model', verbose_name='PRODUCT')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onoxo.raw_material_model', verbose_name='RAW MATERIAL')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.AddField(
            model_name='finished_products_model',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishedProd', to='onoxo.unit_model', verbose_name='UNIT'),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='onoxo.job_title_model', verbose_name='JOB TITLE'),
        ),
    ]
