# Generated by Django 4.1.6 on 2023-05-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onoxo', '0002_credit_model_creditforeverymonth_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditforeverymonth_model',
            options={'ordering': ['-credit', 'dateOfPayment']},
        ),
    ]
