# Generated by Django 4.1.6 on 2023-06-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_passportdatas_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfBirthStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Область')),
                ('village', models.CharField(blank=True, max_length=255, null=True, verbose_name='Село')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_birthstudents', to='students.student')),
            ],
            options={
                'verbose_name': 'Место рождение студента',
                'verbose_name_plural': 'Y| Место рождение студента',
            },
        ),
    ]
