# Generated by Django 4.1.6 on 2023-06-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_trainingstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProficiencyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statelanguage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Знание государственного языка')),
                ('languagesem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык')),
                ('levellang', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уровень знания языка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languageproficiencystudent', to='students.student')),
            ],
            options={
                'verbose_name': 'Знание языков',
                'verbose_name_plural': 'Y| Знание языков',
            },
        ),
    ]
