# Generated by Django 4.1.6 on 2023-06-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_passportdatas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportDataS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedoc', models.CharField(max_length=255, null=True, verbose_name='Вид документа')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('date_of_issue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выдачи')),
                ('date_end', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdata', to='students.student')),
            ],
            options={
                'verbose_name': 'Паспортные данные',
                'verbose_name_plural': 'A| Паспортные данные студентов',
            },
        ),
    ]
