# Generated by Django 4.1.6 on 2023-06-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_passportdatas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityOfStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=250, null=True, verbose_name='Язык обучения')),
                ('formContract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма контракта')),
                ('structSubdivision', models.CharField(blank=True, max_length=255, null=True, verbose_name='Структурное подразделение')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление(специальность)')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Код')),
                ('levelOfEducation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уровень образования')),
                ('qualification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Квалификация')),
                ('form_of_training', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('period_of_training', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок обучения')),
                ('date_registr', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('protokol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Протокол')),
                ('date_recommend', models.DateField(blank=True, null=True, verbose_name='Дата рекомендации')),
                ('date_confirm', models.DateField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('order_Number', models.IntegerField(blank=True, null=True, verbose_name='Номер приказа')),
                ('order_Date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('protokol_Number', models.IntegerField(blank=True, null=True, verbose_name='Номер протокола')),
                ('protokol_Date', models.DateField(blank=True, null=True, verbose_name='Дата протокола')),
                ('documentReturnDate', models.DateField(blank=True, null=True, verbose_name='Дата возрата документа')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialityStudents', to='students.student')),
            ],
            options={
                'verbose_name': 'Специальности студента',
                'verbose_name_plural': 'Специальность студента',
            },
        ),
    ]
